DISABLE_AUTO_UPDATE="true"

source ~/.virtualenv/py3/bin/activate

alias gs='gst'
# alias vi='/usr/local/bin/vim'
alias vi='vim'

alias getpass='openssl rand -base64 20'
alias www='python -m http.server 8000'
alias getip='curl ipinfo.io/ip'

# pip install pygments
function ccat() {
    local style="monokai"
    if [ $# -eq 0 ]; then
        pygmentize -P style=$style -P tabsize=4 -f terminal256 -g
    else
        for NAME in $@; do
            pygmentize -P style=$style -P tabsize=4 -f terminal256 -g "$NAME"
        done
    fi
}

# git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions
plugins=(
  zsh-autosuggestions 
  git
)

alias dp='docker ps -a'
alias dk='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)'
alias dc='docker-compose'
alias di='docker images'
alias dir='docker rmi'

export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles

# in mac
export GOROOT=/usr/local/Cellar/go/1.11.1/libexec
export GOPATH=~/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:/usr/local/Cellar/go/1.11.1/bin/:$GOPATH/bin

# another linux
export GOROOT=/opt/go
export GOPATH=~/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:/opt/go/bin/:$GOPATH/bin
